# Generated by Django 4.0.5 on 2022-06-26 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('uuid', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('parentId', models.TextField()),
                ('name', models.TextField()),
                ('datetime', models.TextField()),
                ('text', models.TextField()),
                ('posType', models.TextField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')])),
                ('price', models.BigIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('children', models.ManyToManyField(to='sales_listener.position')),
            ],
        ),
    ]
