# Generated by Django 4.0.5 on 2022-06-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_listener', '0002_rename_uuid_position_id_rename_postype_position_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='datetime',
            new_name='date',
        ),
    ]
